dist: trusty

language: node_js
node_js:
  - "node"

env:
  - TEST_DIR=frontend

before_install:
  - cd $TEST_DIR
install:
  - npm install

script:
  - npm test

before_deploy:
  - npm run build
  - ls -la
  - tar -cf build.tar ./build/
deploy:
  provider: realeases
  api_key: "faf8bed4f35f3991d76a7e3fdeb15fd4c276e54f"
  skip_cleanup: true
  file: build.tar
#  on:
#    tags: true