dist: trusty

language: node_js
node_js:
  - "node"

env:
  - TEST_DIR=frontend

before_install:
  - cd $TEST_DIR
install:
  - npm install

script:
  - npm test

before_deploy:
  - npm run build
  - tar -cf build.tar ./build/
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: build.tar
#  on:
#    tags: true