version: '2'
services:
 nginx-proxy:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  ports:
   - "80:80"
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock:ro
  environment:
   - DEFAULT_HOST=www.*

 mongodb:
  image: mongo:latest
  container_name: mongodb

 backend:
  image: node:latest
  working_dir: /app
  command: bash -c "node -v && npm install -q && npm start"
  container_name: backend
  depends_on:
   - nginx-proxy
   - mongodb
  links:
   - mongodb
  expose:
   - "4000"
  volumes:
   - ./backend:/app
  environment:
   - VIRTUAL_HOST=api.*
   - VIRTUAL_PORT=4000

 frontend:
  image: node:latest
  working_dir: /app
  command: bash -c "node -v && npm install -q && npm start"
  container_name: frontend
  depends_on:
   - nginx-proxy
   - backend
  expose:
   - "4200"
  ports:
   - "4200:4200"
  volumes:
   - ./frontend:/app
  environment:
   - VIRTUAL_HOST=www.*
   - VIRTUAL_PORT=4200
