version: '2'
services:
 nginx-proxy:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  ports:
   - "80:80"
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock:ro
  environment:
   - DEFAULT_HOST=www.*

 mongodb:
  image: mongo:latest
  container_name: mongodb
  volumes:
   - ./data/db:/data/db

 backend:
  image: node:latest
  working_dir: /app
  command: bash -c "node -v && npm -v && npm start"
  container_name: backend
  links:
   - mongodb
  expose:
   - "4000"
  volumes:
   - ./backend:/app
  environment:
   - VIRTUAL_HOST=api.*

 frontend:
  image: node:latest
  working_dir: /app
  command: bash -c "node -v && npm -v && npm start"
  container_name: frontend
  expose:
   - "3000"
  volumes:
   - ./frontend:/app
  environment:
   - VIRTUAL_HOST=www.*
